# Generated by workbench.yml (brew-tap job) from the app-v0.1.0 release.
# Source of truth: packaging/homebrew/Casks/space-lens.rb in the space-lens repo.
cask "space-lens" do
  arch arm: "aarch64", intel: "x64"

  version "0.1.0"
  sha256 arm:   "2b63c5229a111d5682e27f750ef0edaf333317e60caf054fa5bbb8ff31c7d2fd",
         intel: "6e6d02e71ec249688f070a826f2c0b4b7e8cfe5afe95091230dc95862e4efcec"

  url "https://github.com/HuakunShen/space-lens/releases/download/app-v#{version}/Space.Lens_#{version}_#{arch}.dmg"
  name "Space Lens"
  desc "Local-first disk map: scan any folder and stage cleanup candidates"
  homepage "https://github.com/HuakunShen/space-lens"

  livecheck do
    url "https://github.com/HuakunShen/space-lens/releases/latest"
    strategy :github_latest do |json|
      json["tag_name"]&.sub(/^app-v/, "")
    end
  end

  auto_updates true

  app "Space Lens.app"

  zap trash: [
    "~/Library/Application Support/sh.huakun.spacelens.desktop",
    "~/Library/WebKit/sh.huakun.spacelens.desktop",
  ]
end
