# Generated by workbench.yml (brew-tap job) from the app-v0.2.1 release.
# Source of truth: packaging/homebrew/Casks/space-lens.rb in the space-lens repo.
cask "space-lens" do
  arch arm: "aarch64", intel: "x64"

  version "0.2.1"
  sha256 arm:   "5c60ab4de44deeb056c285e2be6d97ed97b9e57f610f9efe7503f038268a7834",
         intel: "a650da70983763de66133bc21688dbaa0d29235b6bf64a9d13434432266315bb"

  url "https://github.com/HuakunShen/space-lens/releases/download/app-v#{version}/Space.Lens_#{version}_#{arch}.dmg"
  name "Space Lens"
  desc "Local-first disk map: scan any folder and stage cleanup candidates"
  homepage "https://github.com/HuakunShen/space-lens"

  livecheck do
    url "https://github.com/HuakunShen/space-lens/releases/latest"
    strategy :github_latest do |json|
      json["tag_name"]&.sub(/^app-v/, "")
    end
  end

  auto_updates true

  app "Space Lens.app"

  zap trash: [
    "~/Library/Application Support/sh.huakun.spacelens.desktop",
    "~/Library/WebKit/sh.huakun.spacelens.desktop",
  ]
end
