# Generated by workbench.yml (brew-tap job) from the app-v0.3.0 release.
# Source of truth: packaging/homebrew/Casks/space-lens.rb in the space-lens repo.
cask "space-lens" do
  arch arm: "aarch64", intel: "x64"

  version "0.3.0"
  sha256 arm:   "5ee21024deb2fdd0da726aa0b5b82735a38083ce36a3105e640372aec3b87abe",
         intel: "948357841a227924cb838b50c775c305fbc6ee2fb4aa237e78d05f6babbe6e43"

  url "https://github.com/HuakunShen/space-lens/releases/download/app-v#{version}/Space.Lens_#{version}_#{arch}.dmg"
  name "Space Lens"
  desc "Local-first disk map: scan any folder and stage cleanup candidates"
  homepage "https://github.com/HuakunShen/space-lens"

  livecheck do
    url "https://github.com/HuakunShen/space-lens/releases/latest"
    strategy :github_latest do |json|
      json["tag_name"]&.sub(/^app-v/, "")
    end
  end

  auto_updates true

  app "Space Lens.app"

  zap trash: [
    "~/Library/Application Support/sh.huakun.spacelens.desktop",
    "~/Library/WebKit/sh.huakun.spacelens.desktop",
  ]
end
