# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bread < Formula
  desc "Bounded batch file reader for coding agents"
  homepage "https://github.com/HuakunShen/bread"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HuakunShen/bread/releases/download/v0.2.1/bread_0.2.1_darwin_amd64.tar.gz"
      sha256 "dff885eada31aacb746d6efed86e2bb6859697b1544504194a8569d538a9a469"

      define_method(:install) do
        bin.install "bread"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HuakunShen/bread/releases/download/v0.2.1/bread_0.2.1_darwin_arm64.tar.gz"
      sha256 "5a64a1b090a2b6b1f179b812767f675a7a10eaf582ffa3ab768acc1c5973f43e"

      define_method(:install) do
        bin.install "bread"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HuakunShen/bread/releases/download/v0.2.1/bread_0.2.1_linux_amd64.tar.gz"
      sha256 "9deab2671fe8fb5168a8e03324713ec975b0036a1e264873e2455dabff3ba34b"
      define_method(:install) do
        bin.install "bread"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HuakunShen/bread/releases/download/v0.2.1/bread_0.2.1_linux_arm64.tar.gz"
      sha256 "aa1620e91154f2e5b666770d8db732ed80f71f467e0171ec1e0a8e17479270b0"
      define_method(:install) do
        bin.install "bread"
      end
    end
  end
end
